# Copyright Red Hat
# Run `make samples` if you modified the orginal file located in the project resources directory
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterregistrar-role
subjects:
- kind: ServiceAccount
  name: "{{ .multicontent.ServiceAccount }}"
  namespace: {{ .multicontent.ServiceAccount }}
